version: 2.1
orbs: #declare the orbs that will be used for the project. These instructions will instruct the server to setup specific software on the server executing our pipeline
  node: circleci/node@5.0.0 #using the node configuration orb for the project
  aws-cli: circleci/aws-cli@2.0.6 #using aws cli orb
  eb: circleci/aws-elastic-beanstalk@2.0.1 #using the elastic beanstalk orb
jobs: #Jobs are groups of commands that we want to run. This is where we will run commands to install, build or deploy our application.
  build: #build the project to a docker container
    docker: 
      - image: "cimg/base:stable" #an Ubuntu Docker image created by circleci
    steps:
      - checkout #getting the code and downloading it
      - node/install #installing the project dependencies
        node-version: '14.16.1'
      - aws-cli/setup
      - eb/setup
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
      - run:
          name: Back-End Install
          command: |
            npm run backend:install
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          name: Back-End Build
          command: |
            npm run backend:build
      - run:
          name: App Test
          command: |
            npm run test
      - run:
          name: Deploy API
          command: |
            npm run backend:deploy
      - run:
          name: Deploy App
          command: |
            npm run frontend:deploy