version: 2.1
#declare the orbs that will be used for the project. These instructions will instruct the server to setup specific software on the server executing our pipeline
orbs: 
  node: circleci/node@5.0.0 #using the node configuration orb for the project
  aws-cli: circleci/aws-cli@2.0.6 #using aws cli orb
  eb: circleci/aws-elastic-beanstalk@2.0.1 #using the elastic beanstalk orb
#Jobs are groups of commands that we want to run. This is where we will run commands to install, build or deploy our application.
jobs: 
  build: 
    docker: 
      - image: "cimg/base:stable" 
    steps:
      - checkout 
      - node/install 
      - aws-cli/setup
      - eb/setup
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
      - run:
          name: Back-End Install
          command: |
            npm run backend:install
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          name: Back-End Build
          command: |
            npm run backend:build
      - run:
          name: App Test
          command: |
            npm run test
      - run:
          name: Deploy API
          command: |
            npm run backend:deploy
      - run:
          name: Deploy App
          command: |
            npm run frontend:deploy